# Generated by Django 5.2.2 on 2025-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_options_remove_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
